### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by Ve0** [retspen/webvirtcloud#124]
I just upgrade from ubuntu 14.04 to 16.04 and WVC stop working. I update all sturtup scripts to systemd.
So...
When I run manualy:  /srv/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /srv/webvirtcloud/gunicorn.conf.py

I get this one:
bash: /srv/webvirtcloud/venv/bin/gunicorn: /srv/webvirtcloud/venv/bin/python: bad interpreter: Too many levels of symbolic links

**Comment by savichev** [comment]
Hi!
Re- run this commands
```
cd /srv/webvirtcloud
virtualenv venv
source venv/bin/activate
pip install -r conf/requirements.txt
```

**Comment by Ve0** [comment]
Thank you so much, but it doesn't help. I get another error:

root@vmhost:/srv/webvirtcloud# virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /srv/webvirtcloud/venv/bin/python2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 942, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1261, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 40] Too many levels of symbolic links: '/srv/webvirtcloud/venv/bin/python2'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ImportError: No module named apport.fileutils

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 942, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1261, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 40] Too many levels of symbolic links: '/srv/webvirtcloud/venv/bin/python2'
root@vmhost:/srv/webvirtcloud#

**Comment by savichev** [comment]
python3

**Comment by alexsalex** [comment]
Nope.... Get this:

(venv)root@vmhost:/srv/webvirtcloud# virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /srv/webvirtcloud/venv/bin/python2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 942, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1261, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 40] Too many levels of symbolic links: '/srv/webvirtcloud/venv/bin/python2'

**Comment by alexsalex** [comment]
any idea? Ubuntu released 16.04.01 LTS..... And I still can not start WebVirtCloud...
