### ISSUE TITLE
 supervisord process 'webvirtcloud' Exited too quickly

### ISSUE THREAD

**Issue by pentacore** [retspen/webvirtcloud#246]
OS: CentOS 7

After following the install instructions to install webvirtcloud and i try to start supervisord i get the following with `supervisord status`
```bash
[penta@pentavm ~]$ sudo supervisorctl status
novncd                           RUNNING   pid 28289, uptime 0:00:19
webvirtcloud                     FATAL     Exited too quickly (process log may have details)
```
And checking the process log gives the following:
```bash
[penta@pentavm ~]$ sudo supervisorctl tail webvirtcloud
supervisor: couldn't exec /srv/webvirtcloud/venv/bin/gunicorn: ENOENT
supervisor: child process was not spawned
supervisor: couldn't exec /srv/webvirtcloud/venv/bin/gunicorn: ENOENT
supervisor: child process was not spawned
supervisor: couldn't exec /srv/webvirtcloud/venv/bin/gunicorn: ENOENT
supervisor: child process was not spawned
supervisor: couldn't exec /srv/webvirtcloud/venv/bin/gunicorn: ENOENT
supervisor: child process was not spawned
```

No other errors as far as i can see, and I'm at my wits end

**Comment by catborise** [comment]
can you run this command and send us its output pls.

/srv/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /srv/webvirtcloud/gunicorn.conf.py

**Comment by pentacore** [comment]
```bash
[penta@pentavm ~]$ /srv/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /srv/webvirtcloud/gunicorn.conf.py
-bash: /srv/webvirtcloud/venv/bin/gunicorn: /var/lib/libvirt/boot/webvirtcloud/venv/bin/python: bad interpreter: No such file or directory
```
Guess a step or two is missing from the [wiki](https://github.com/retspen/webvirtcloud/wiki/CentOS-7-installation)

**Comment by catborise** [comment]
i am using main readme file for installation. this works, i never used wiki page for installation. i will check it.
https://github.com/retspen/webvirtcloud

**Comment by pentacore** [comment]
Yea i followed that to begin with, but got the same result, then i found the Wiki and tried using that.
No, Am i supposed to do that? didnt see any step to do that.

Ah, yea i know docker, just somehow missed that there was an image for it

**Comment by catborise** [comment]
no you should not. but something wrong with installation. and your setup is not same as told in readme. python seeks that path "/var/lib/libvirt/boot/webvirtcloud/venv/bin/python" but this should not happen. but actually python should in that path "/srv/webvirtcloud/venv/bin/".

i think there are some virtualenv mishaps.

**Comment by pentacore** [comment]
Interesting, as far as i know i havent changed any paths. and most steps in the Wiki seems to be the same as in the readme

**Comment by pentacore** [comment]
Tried the Docker path but i cant build the image..

``` 
Step 8/19 : RUN cd /srv/webvirtcloud && 	virtualenv venv && 	. venv/bin/activate && 	pip install -U pip && 	pip install -r conf/requirements.txt && 	chown -R www-data:www-data /srv/webvirtcloud
 ---> Running in c78cca76ba69
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 985, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1179, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 478, in copyfile
    copyfileordir(src, dest, symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 453, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/usr/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'venv/lib/python2.7/lib-dynload'
The command '/bin/sh -c cd /srv/webvirtcloud && 	virtualenv venv && 	. venv/bin/activate && 	pip install -U pip && 	pip install -r conf/requirements.txt && 	chown -R www-data:www-data /srv/webvirtcloud' returned a non-zero code: 1

```

**Comment by catborise** [comment]
i tested again like below no problem on centos7 vm.
1. git clone https://github.com/retspen/webvirtcloud.git
2.  cd webvirtcloud/
3.  cp webvirtcloud/settings.py.template webvirtcloud/settings.py
4. Generate random number:
>>>python
Python 2.7.5 (default, Oct 30 2018, 23:45:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import random, string
>>> haystack = string.ascii_letters + string.digits + string.punctuation
>>> print(''.join([random.SystemRandom().choice(haystack) for _ in range(50)]))
V!!(nO]LgiuuYDLd%uHlz:830bT,GzWIS-xRI[BPTdDb=fV"?X
>>> exit()
5. copy random number and paste it to settings.py as SECRET_KEY = '<random>'
6.  docker build -t retspen/webvirtcloud:0.1 .
Sending build context to Docker daemon  12.92MB
Step 1/19 : FROM phusion/baseimage:0.11
 ---> 14e6c478b00a
Step 2/19 : MAINTAINER Jethro Yu <comet.jc@gmail.com>
 ---> Using cache
 ---> 7e32a823f865
Step 3/19 : RUN echo 'APT::Get::Clean=always;' >> /etc/apt/apt.conf.d/99AutomaticClean
 ---> Using cache
 ---> 6b5c4d8c1be5
Step 4/19 : RUN apt-get update -qqy
 ---> Using cache
 ---> fabac3597439
Step 5/19 : RUN DEBIAN_FRONTEND=noninteractive apt-get -qyy install     -o APT::Install-Suggests=false  git python-virtualenv python-dev python-lxml libvirt-dev zlib1g-dev nginx libsasl2-modules
 ---> Using cache
 ---> a059018fdc1d
Step 6/19 : ADD . /srv/webvirtcloud
 ---> 36272cad2cf4
Step 7/19 : RUN chown -R www-data:www-data /srv/webvirtcloud
 ---> Running in 4929207fe8d7
Removing intermediate container 4929207fe8d7
 ---> 925f22821061
Step 8/19 : RUN cd /srv/webvirtcloud &&         virtualenv venv &&      . venv/bin/activate &&  pip install -U pip &&   pip install -r conf/requirements.txt &&         chown -R www-data:www-data /srv/webvirtcloud
 ---> Running in a6a64d771afa
New python executable in /srv/webvirtcloud/venv/bin/python2
Also creating executable in /srv/webvirtcloud/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pip in ./venv/lib/python2.7/site-packages (19.1.1)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting Django==1.11.21 (from -r conf/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a2/84/9f66e359ba8e63cf9b54f6815ed55188dda43cd1cc951a8bb95542dee956/Django-1.11.21-py2.py3-none-any.whl (6.9MB)
Collecting websockify==0.8.0 (from -r conf/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/66/48/2e35166c957639ddb4cb11ce9783ad3ee9bf96f220354ce2684ee95feeb7/websockify-0.8.0.tar.gz (234kB)
Collecting gunicorn==19.9.0 (from -r conf/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl (112kB)
Collecting lxml==4.2.5 (from -r conf/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/e5/14/f4343239f955442da9da1919a99f7311bc5627522741bada61b2349c8def/lxml-4.2.5-cp27-cp27mu-manylinux1_x86_64.whl (5.8MB)
Collecting libvirt-python==5.3.0 (from -r conf/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/77/85/552efa34812f9b7f18e35f9eac1b680df54bed302ddfd7d08915a8a75906/libvirt-python-5.3.0.tar.gz (193kB)
Collecting pytz (from -r conf/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
Collecting rwlock (from -r conf/requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/4b/1b/333059f7a18180ded504e799b9fea96e9ad7ed6af74039adf542fb93e433/rwlock-0.0.7.tar.gz
Collecting numpy (from websockify==0.8.0->-r conf/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/1f/c7/198496417c9c2f6226616cff7dedf2115a4f4d0276613bab842ec8ac1e23/numpy-1.16.4-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
Building wheels for collected packages: websockify, libvirt-python, rwlock
  Building wheel for websockify (setup.py): started
  Building wheel for websockify (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/67/ec/b2/08efd6524556d805fb2df3366bd2eb1e57490e015ab9835a0a
  Building wheel for libvirt-python (setup.py): started
  Building wheel for libvirt-python (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/6f/c2/fd/93d810b7ee07cbbf707bb40d507fa8e9591cc33a0605287b9b
  Building wheel for rwlock (setup.py): started
  Building wheel for rwlock (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f6/96/55/ee5e72c5e8d4b238f1bc354d2fa999083c1eab7c69a14ea3e2
Successfully built websockify libvirt-python rwlock
Installing collected packages: pytz, Django, numpy, websockify, gunicorn, lxml, libvirt-python, rwlock
Successfully installed Django-1.11.21 gunicorn-19.9.0 libvirt-python-5.3.0 lxml-4.2.5 numpy-1.16.4 pytz-2019.1 rwlock-0.0.7 websockify-0.8.0
Removing intermediate container a6a64d771afa
 ---> ceb4dd1baa76
Step 9/19 : RUN cd /srv/webvirtcloud && . venv/bin/activate &&  python manage.py migrate &&     chown -R www-data:www-data /srv/webvirtcloud
 ---> Running in 9300bcb8d104
Operations to perform:
  Apply all migrations: accounts, admin, auth, computes, contenttypes, create, instances, logs, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying computes.0001_initial... OK
  Applying instances.0001_initial... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20150325_0846... OK
  Applying accounts.0003_usersshkey... OK
  Applying accounts.0004_userattributes... OK
  Applying accounts.0005_userattributes_can_clone_instances... OK
  Applying accounts.0006_userattributes_max_disk_size... OK
  Applying accounts.0007_auto_20160426_0635... OK
  Applying accounts.0004_userinstance_is_vnc... OK
  Applying accounts.0008_merge... OK
  Applying accounts.0009_auto_20171026_0805... OK
  Applying accounts.0010_auto_20180625_1236... OK
  Applying accounts.0011_auto_20180625_1313... OK
  Applying accounts.0012_auto_20180625_1331... OK
  Applying accounts.0013_auto_20180625_1358... OK
  Applying accounts.0014_auto_20180808_1436... OK
  Applying accounts.0015_auto_20180808_1449... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying computes.0002_compute_details... OK
  Applying create.0001_initial... OK
  Applying create.0002_auto_20150325_0921... OK
  Applying instances.0002_instance_is_template... OK
  Applying instances.0003_instance_created... OK
  Applying instances.0004_auto_20180724_1136... OK
  Applying logs.0001_initial... OK
  Applying logs.0002_auto_20150316_1420... OK
  Applying logs.0003_auto_20150518_1855... OK
  Applying sessions.0001_initial... OK
Removing intermediate container 9300bcb8d104
 ---> 8807647227ad
Step 10/19 : RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf &&       rm /etc/nginx/sites-enabled/default &&  chown -R www-data:www-data /var/lib/nginx
 ---> Running in 147bebca37bc
Removing intermediate container 147bebca37bc
 ---> 9f7c9016afef
Step 11/19 : ADD conf/nginx/webvirtcloud.conf /etc/nginx/conf.d/
 ---> 2e96e263d227
Step 12/19 : RUN        mkdir /etc/service/nginx &&     mkdir /etc/service/nginx-log-forwarder &&       mkdir /etc/service/webvirtcloud &&      mkdir /etc/service/novnc
 ---> Running in 4dd9b038b927
Removing intermediate container 4dd9b038b927
 ---> 8f4ee1ecccdf
Step 13/19 : ADD conf/runit/nginx                       /etc/service/nginx/run
 ---> a27013bf8aa4
Step 14/19 : ADD conf/runit/nginx-log-forwarder /etc/service/nginx-log-forwarder/run
 ---> f8f103065768
Step 15/19 : ADD conf/runit/novncd.sh           /etc/service/novnc/run
 ---> 2d07f6bc56ca
Step 16/19 : ADD conf/runit/webvirtcloud.sh             /etc/service/webvirtcloud/run
 ---> 78980c5f27c4
Step 17/19 : EXPOSE 80
 ---> Running in c22fe384f384
Removing intermediate container c22fe384f384
 ---> 7e0112ca310a
Step 18/19 : EXPOSE 6080
 ---> Running in 3ed5023301e1
Removing intermediate container 3ed5023301e1
 ---> 5b086b5cc723
Step 19/19 : CMD ["/sbin/my_init"]
 ---> Running in 9eae226c4b12
Removing intermediate container 9eae226c4b12
 ---> 71c15cdae674
Successfully built 71c15cdae674

7. docker run -d -p 80:80 -p 6080:6080 retspen/webvirtcloud:0.1

it works as expected....

**Comment by pentacore** [comment]
Interesting that your  `Sending build context to Docker daemon` size is ~120mb smaller than mine... i've got no idea whats happening here

**Comment by catborise** [comment]
please try it with clean install...
- create a vm
- install a centos7 and update it
- install docker latest
- try it again.

probably your old config breaks something.
