### ISSUE TITLE
[ERROR] Error handling request /admin/users/create/

### ISSUE THREAD

**Issue by aiminickwong** [retspen/webvirtcloud#353]
```
Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/webvirtcloud/admin/decorators.py", line 8, in _inner
    return function(request, *args, **kwargs)
  File "/srv/webvirtcloud/admin/views.py", line 113, in user_create
    'title': _('Create User')
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/bootstrap4/templatetags/bootstrap4.py", line 454, in bootstrap_form
    return render_form(*args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/bootstrap4/forms.py", line 27, in render_form
    return renderer_cls(form, **kwargs).render()
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/bootstrap4/renderers.py", line 84, in render
    return mark_safe(self._render())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/bootstrap4/renderers.py", line 203, in _render
    return self.render_errors(self.alert_error_type) + self.render_fields()
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/bootstrap4/renderers.py", line 155, in render_fields
    for field in self.form:
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/forms/forms.py", line 158, in __iter__
    yield self[name]
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/forms/forms.py", line 173, in __getitem__
    self._bound_fields_cache[name] = field.get_bound_field(self, name)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/forms/fields.py", line 198, in get_bound_field
    return BoundField(form, self, field_name)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/forms/boundfield.py", line 27, in __init__
    self.help_text = field.help_text or ''
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/functional.py", line 151, in __wrapper__
    res = func(*self.__args, **self.__kw)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/text.py", line 413, in _format_lazy
    return format_string.format(*args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/functional.py", line 152, in __wrapper__
    return getattr(res, method_name)(*args, **kw)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/functional.py", line 156, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user_update_password' with arguments '(None,)' not found. 1 pattern(s) tried: ['admin\\/users\\/(?P<pk>[0-9]+)\\/update_password\\/$']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/webvirtcloud/webvirtcloud/middleware.py", line 15, in __call__
    return self.get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/views/defaults.py", line 80, in server_error
    return HttpResponseServerError(template.render())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/srv/webvirtcloud/webvirtcloud/common_tags.py", line 23, in class_active
    if re.search(pattern, request.path):
AttributeError: 'str' object has no attribute 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/webvirtcloud/appsettings/middleware.py", line 10, in __call__
    return self.get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/views/defaults.py", line 80, in server_error
    return HttpResponseServerError(template.render())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/srv/webvirtcloud/webvirtcloud/common_tags.py", line 23, in class_active
    if re.search(pattern, request.path):
AttributeError: 'str' object has no attribute 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/views/defaults.py", line 80, in server_error
    return HttpResponseServerError(template.render())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/srv/webvirtcloud/webvirtcloud/common_tags.py", line 23, in class_active
    if re.search(pattern, request.path):
AttributeError: 'str' object has no attribute 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/views/defaults.py", line 80, in server_error
    return HttpResponseServerError(template.render())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/srv/webvirtcloud/webvirtcloud/common_tags.py", line 23, in class_active
    if re.search(pattern, request.path):
AttributeError: 'str' object has no attribute 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/views/defaults.py", line 80, in server_error
    return HttpResponseServerError(template.render())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/srv/webvirtcloud/webvirtcloud/common_tags.py", line 23, in class_active
    if re.search(pattern, request.path):
AttributeError: 'str' object has no attribute 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/views/defaults.py", line 80, in server_error
    return HttpResponseServerError(template.render())
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/srv/webvirtcloud/webvirtcloud/common_tags.py", line 23, in class_active
    if re.search(pattern, request.path):
AttributeError: 'str' object has no attribute 'path'
```

**Comment by aiminickwong** [comment]
I have tested the newest version from master repo.

**Comment by aiminickwong** [comment]
django.urls.exceptions.NoReverseMatch: Reverse for 'user_update_password' with arguments '(None,)' not found. 1 pattern(s) tried: ['admin\\/users\\/(?P<pk>[0-9]+)\\/update_password\\/$']

During handling of the above exception, another exception occurred:

I think that is the reson.

**Comment by catborise** [comment]
i have created many user without problem but they are not admin user. can you create non admin user.?

**Comment by aiminickwong** [comment]
Yes, it's fixed.
