### ISSUE TITLE
migration failed

### ISSUE THREAD

**Issue by pytker** [retspen/webvirtcloud#356]
Hi.

I get errors when run migrations.

```sh
webvirtcloud /usr/bin/python3 /webvirtcloud/manage.py migrate -v3
Operations to perform:
  Apply all migrations: accounts, admin, appsettings, auth, computes, contenttypes, instances, logs, sessions
Running pre-migrate handlers for application auth
Running pre-migrate handlers for application contenttypes
Running pre-migrate handlers for application sessions
Running pre-migrate handlers for application bootstrap4
Running pre-migrate handlers for application accounts
Running pre-migrate handlers for application admin
Running pre-migrate handlers for application appsettings
Running pre-migrate handlers for application computes
Running pre-migrate handlers for application console
Running pre-migrate handlers for application datasource
Running pre-migrate handlers for application networks
Running pre-migrate handlers for application instances
Running pre-migrate handlers for application interfaces
Running pre-migrate handlers for application nwfilters
Running pre-migrate handlers for application storages
Running pre-migrate handlers for application secrets
Running pre-migrate handlers for application logs
Running migrations:
  Applying computes.0001_initial... OK (0.926s)
  Applying instances.0001_initial... OK (1.019s)
  Applying instances.0002_permissionset... OK (0.149s)
  Applying instances.0003_auto_20200615_0637... OK (0.152s)
  Applying contenttypes.0001_initial... OK (0.681s)
  Applying auth.0001_initial... OK (5.464s)
  Applying accounts.0001_initial... OK (5.840s)
  Applying accounts.0002_permissionset... OK (0.143s)
  Applying accounts.0003_auto_20200604_0930... OK (0.196s)
  Applying accounts.0004_auto_20200615_0637... OK (0.240s)
  Applying accounts.0005_auto_20200616_1039... OK (0.287s)
  Applying contenttypes.0002_remove_content_type_name... OK (0.679s)
  Applying auth.0002_alter_permission_name_max_length... OK (0.343s)
  Applying auth.0003_alter_user_email_max_length... OK (0.237s)
  Applying auth.0004_alter_user_username_opts... OK (0.180s)
  Applying auth.0005_alter_user_last_login_null... OK (0.298s)
  Applying auth.0006_require_contenttypes_0002... OK (0.143s)
  Applying auth.0007_alter_validators_add_error_messages... OK (0.211s)
  Applying auth.0008_alter_user_username_max_length... OK (0.355s)
  Applying auth.0009_alter_user_last_name_max_length... OK (0.349s)
  Applying auth.0010_alter_group_name_max_length... OK (0.263s)
  Applying auth.0011_update_proxy_permissions... OK (0.361s)
  Applying admin.0001_initial... OK (0.151s)
  Applying admin.0002_auto_20200609_0830... OK (0.140s)
  Applying appsettings.0001_initial... OK (0.656s)
  Applying appsettings.0002_auto_20200527_1603...Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'choices' at row 10")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/webvirtcloud/manage.py", line 21, in <module>
    main()
  File "/webvirtcloud/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 121, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/webvirtcloud/appsettings/migrations/0002_auto_20200527_1603.py", line 35, in add_default_settings
    setting(26, _("Show Access SSH Keys"), "SHOW_ACCESS_SSH_KEYS", "False", "True,False", _("Show access ssh keys")),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 468, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1211, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 31setting(10, _("Disk Cache"), "INSTANCE_VOLUME_DEFAULT_CACHE", "directsync", "default,directsync,none,unsafe,writeback,writethrough", _("Disk volume cache type")),9, in _query
    db.query(q)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'choices' at row 10")

```
In file  appsettings/migrations/0002_auto_20200527_1603.py in row     setting(10, _("Disk Cache"), "INSTANCE_VOLUME_DEFAULT_CACHE", "directsync", "default,directsync,none,unsafe,writeback,writethrough", _("Disk volume cache type")),   value default,directsync,none,unsafe,writeback,writethrough - longer than 50

I use mysql as db.

**Comment by catborise** [comment]
@pytker thanks i made it 70. will create commit
