### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by lmsdscav** [retspen/webvirtcloud#507]
it says 500 error if i opened user configuration.
and it will also be 500 if i connected ssh and opened "Instances" tab.

How can i fix it?:(
![Uploading Screenshot_20220626-165515381.png…]()

**Comment by lmsdscav** [comment]
![Screenshot_20220626-165515381](https://user-images.githubusercontent.com/46647597/175806976-d1301ccc-929b-44ba-ad4a-f1207b68c295.png)

**Comment by catborise** [comment]
if you update it lately. you should run `python manage.py makemigrations; python manage.py migrate` commands

**Comment by pysiek634** [comment]
I have the same problem on clean ubuntu 20.04 installation.

**Comment by pysiek634** [comment]
Debug=true  shows missing instances_instance.drbd column in sqlite database.
After fresh installation!
python3 manage.py migrate 
was usefull for me.

**Comment by gilbertoferreira** [comment]
srv1:/srv/webvirtcloud# python3 manage.py migrate
Traceback (most recent call last):
  File "/srv/webvirtcloud/manage.py", line 21, in <module>
    main()
  File "/srv/webvirtcloud/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python3/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_bootstrap5'


Debian 11

**Comment by gilbertoferreira** [comment]
SOLVED
  134  pip install django-bootstrap5
  135  python3 manage.py migrate
  136  pip install django-icons
  137  python3 manage.py migrate

**Comment by catborise** [comment]
@gilbertoferreira you should install requirements with `pip3 install -r conf/requirements.txt` .

**Comment by gilbertoferreira** [comment]
> @gilbertoferreira you should install requirements with `pip3 install -r conf/requirements.txt` .

Yes! I do that following the installation instructions. But nevertheless after install it give the 500 error! Just solved after do the above
