### ISSUE TITLE
Cannot edit LDAP-user

### ISSUE THREAD

**Issue by thofram** [retspen/webvirtcloud#602]
When I try to edit a user created by LDAP-logon, I get this error:
ERROR: Internal Server Error: /admin/users/2/update/

I cannot make this LDAP user an admin.

**Comment by thofram** [comment]
From /srv/webvirtcloud/webvirtcloud.log:

`[2023-09-22 15:26:33,112] ERROR: Internal Server Error: /admin/users/2/update/
Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/webvirtcloud/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/webvirtcloud/admin/decorators.py", line 8, in _inner
    return function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/webvirtcloud/admin/views.py", line 120, in user_update
    attributes = UserAttributes.objects.get(user=user)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/webvirtcloud/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/webvirtcloud/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
accounts.models.UserAttributes.DoesNotExist: UserAttributes matching query does not exist.`

**Comment by catborise** [comment]
@krejcar25 do you have any fix/recommendation. Thanks

**Comment by krejcar25** [comment]
will check tomorrow @catborise @thofram

**Comment by krejcar25** [comment]
this is caused by incorrect use of Django User models. developers are supposed to extend the builtin User model and add attributes this way ([doc](https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#extending-the-existing-user-model)). the way it's implemented here is through a sidecar model which django-auth-ldap does not know it should create. i will try and find a workaround.

**Comment by thofram** [comment]
Thank you, I can edit the userprofiles of LDAP-users now.
