### ISSUE TITLE
Error with python 3.12

### ISSUE THREAD

**Issue by oukb** [retspen/webvirtcloud#625]
Hi

Fedora 39, Python 3.12, master branch  

```
# python manage.py test
Traceback (most recent call last):
  File "/var/www/webvirtcloud/manage.py", line 21, in <module>
    main()
  File "/var/www/webvirtcloud/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/var/www/webvirtcloud/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/www/webvirtcloud/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/var/www/webvirtcloud/venv/lib64/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/webvirtcloud/venv/lib64/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webvirtcloud/venv/lib64/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/www/webvirtcloud/venv/lib64/python3.12/site-packages/drf_yasg/__init__.py", line 2, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by oukb** [comment]
fixed by installing setuptools
