### ISSUE TITLE
No module named 'zoneinfo'

### ISSUE THREAD

**Issue by gywndi** [retspen/webvirtcloud#641]
Hi

I'm installing webvirtcloud to manage kvm with manual on README.
But I've got in problem relative with "zoneinfo". (My box is running with Ubuntu 20.04.6 LTS)

I changed python3 version from 3.8 to 3.11, but not working.
```
Traceback (most recent call last):
  File "/srv/webvirtcloud/manage.py", line 21, in <module>
    main()
  File "/srv/webvirtcloud/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/core/checks/templates.py", line 60, in check_for_template_tags_with_the_same_name
    for module_name, module_path in get_template_tag_modules():
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 105, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "/srv/webvirtcloud/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 130, in get_package_libraries
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'qr_code.templatetags.qr_code': No module named 'zoneinfo'
```

**Comment by Ryan-dev-design** [comment]
maybe you need to modify the python3 softlink under /usr/bin to make sure the shell script use the right version of python? It seems that you are still using python 3.8 according to the errors

**Comment by jbguo424** [comment]
vi /srv/webvirtcloud/venv/lib/python3.8/site-packages/qr_code/qrcode/utils.py
"""Utility classes and functions for configuring and setting up the content and the look of a QR code."""
import datetime
import decimal
from collections import namedtuple
from dataclasses import asdict
from datetime import date
from decimal import Decimal
from enum import Enum
from typing import Optional, Any, Union, Sequence, List, Tuple

#import zoneinfo
_**from backports.zoneinfo import ZoneInfo as zoneinfo**_

I fixed it using this
