### ISSUE TITLE
Error while "sudo pip install -r conf/requirements.txt"

### ISSUE THREAD

**Issue by jaydeepjc** [retspen/webvirtcloud#96]
sudo pip install -r conf/requirements.txt
sudo: unable to resolve host admin-IPT-M3800
Downloading/unpacking http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz (from -r conf/requirements.txt (line 5))
  Downloading libxml2-python-2.9.1.tar.gz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 643, in unpack_file
    untar_file(filename, location)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 561, in untar_file
    tar = tarfile.open(filename, mode)
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
    raise ReadError("not a gzip file")
ReadError: not a gzip file

Storing debug log for failure in /home/jaydeep/.pip/pip.log

**Comment by savichev** [comment]
Hi!
```
pip --version
```
```
sudo pip install --upgrade pip
```

**Comment by jaydeepjc** [comment]
pip --version
pip 1.5.4 from /srv/webvirtcloud/venv/local/lib/python2.7/site-packages (python 2.7)


sudo pip install --upgrade pip
[sudo] password for jaydeep: 
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-8.1.1-py2.py3-none-any.whl#md5=22db7b6a517a09c29d54a76650f170eb
  Downloading pip-8.1.1-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...


sudo pip install -r conf/requirements.txt
The directory '/home/jaydeep/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jaydeep/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz (from -r conf/requirements.txt (line 5))
  Downloading http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 577, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 653, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 538, in untar_file
    tar = tarfile.open(filename, mode)
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
    raise ReadError("not a gzip file")
ReadError: not a gzip file
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by savichev** [comment]
What name distr linux you use

**Comment by jaydeepjc** [comment]
Ubuntu 14.04 Desktop

**Comment by savichev** [comment]
```
wget https://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz
```
```
tar xfzv libxml2-python-2.9.1.tar.gz
```

**Comment by jaydeepjc** [comment]
Yes, I was able to download it and extracted..
How do I need to proceed further

shall I execute pip install -r conf/requirements.txt in /srv/webvirtmgr folder?

**Comment by savichev** [comment]
yes

**Comment by jaydeepjc** [comment]
After actracting libxml2-python-2.9.1.tar.gz in /srv/webvirtcloud I have executed 
pip install -r conf/requirements.txt  

Still getting same problem.

**Comment by jaydeepjc** [comment]
then I just then into conf folder and and ran 

sudo pip install -r requirements.txt

The directory '/home/jaydeep/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jaydeep/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz (from -r requirements.txt (line 5))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz (265kB)
    100% |████████████████████████████████| 266kB 414kB/s 
  Requirement already satisfied (use --upgrade to upgrade): libxml2-python==2.9.1 from http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): Django==1.8.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): websockify==0.6.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): gunicorn==19.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): libvirt-python==1.2.16 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from websockify==0.6.0->-r requirements.txt (line 2))

is this OK or we still having some issue?

**Comment by savichev** [comment]
is this OK.

**Comment by jaydeepjc** [comment]
Thanks..

After This I have executed below commands as per doc

python manage.py migrate
sudo chown -R www-data:www-data /srv/webvirtcloud
sudo rm /etc/nginx/sites-enabled/default

sudo service nginx restart
sudo service supervisor restart

wget -O - https://clck.ru/9V9fH | sudo sh

However When I tried to open http://machineIP it gives 502 Bad Gateway

Nginx Logs
2016/03/29 17:11:51 [error] 10632#0: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 10.3.2.30, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "10.3.2.30"
2016/03/29 17:11:51 [error] 10632#0: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 10.3.2.30, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8000/favicon.ico", host: "10.3.2.30", referrer: "http://10.3.2.30/"

**Comment by savichev** [comment]
sudo service libvirtd start

**Comment by jaydeepjc** [comment]
I did
sudo service libvirt-bin status
libvirt-bin start/running, process 11226

Still getting same 502 page

**Comment by savichev** [comment]
```
$> supervisorctl
```

**Comment by jaydeepjc** [comment]
supervisorctl
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 224
supervisor>

**Comment by savichev** [comment]
hmm... ok
```
sudo supervisorctl
```

**Comment by jaydeepjc** [comment]
sudo supervisorctl
gstfsd                           RUNNING    pid 11592, uptime 0:05:01
novncd                           FATAL      Exited too quickly (process log may have details)
webvirtcloud                     FATAL      can't find command '/srv/webvirtcloud/venv/bin/gunicorn'
supervisor>

**Comment by savichev** [comment]
```
cd /srv/webvirtcloud
virtualenv venv
source venv/bin/activate
pip install -r conf/requirements.txt
python manage.py migrate
```

**Comment by jaydeepjc** [comment]
sudo virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip...done.

source venv/bin/activate

pip install -r conf/requirements.txt (This command is still having same issue, dont know why)

sudo python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages
  Apply all migrations: logs, sessions, admin, create, contenttypes, auth, instances, computes, accounts
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.

**Comment by savichev** [comment]
ok.. fresh install
```
rm -rf /srv/webvirtcloud/venv
```

```
sudo chown -R www-data:www-data /srv/webvirtcloud
cd /srv/webvirtcloud
virtualenv venv
source venv/bin/activate
pip install -r conf/requirements.txt
python manage.py migrate
sudo chown -R www-data:www-data /srv/webvirtcloud
```

```
ls -la /srv/webvirtcloud/venv/bin/
```

**Comment by jaydeepjc** [comment]
root@admin-IPT-M3800:~# rm -rf /srv/webvirtcloud/venv
root@admin-IPT-M3800:~# chown -R www-data:www-data /srv/webvirtcloud
root@admin-IPT-M3800:~# cd /srv/webvirtcloud
root@admin-IPT-M3800:/srv/webvirtcloud# virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip...
done.
root@admin-IPT-M3800:/srv/webvirtcloud# 
root@admin-IPT-M3800:/srv/webvirtcloud# source venv/bin/activate
(venv)root@admin-IPT-M3800:/srv/webvirtcloud# pip install -r conf/requirements.txt
Downloading/unpacking http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz (from -r conf/requirements.txt (line 5))
  Downloading libxml2-python-2.9.1.tar.gz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/util.py", line 543, in untar_file
    tar = tarfile.open(filename, mode)
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
    raise ReadError("not a gzip file")
ReadError: not a gzip file

Storing debug log for failure in /root/.pip/pip.log
(venv)root@admin-IPT-M3800:/srv/webvirtcloud# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by savichev** [comment]
```
cd /srv/webvirtcloud
source venv/bin/activate
(venv)woof@host:/srv/webvirtcloud$ sudo venv/bin/pip install --upgrade gunicorn==19.3.0
(venv)woof@host:/srv/webvirtcloud$ ls -la venv/bin/
```

**Comment by jaydeepjc** [comment]
venv/bin/pip install --upgrade gunicorn==19.3.0
Downloading/unpacking gunicorn==19.3.0
  Downloading gunicorn-19.3.0-py2.py3-none-any.whl (110kB): 110kB downloaded
Installing collected packages: gunicorn
Compiling /srv/webvirtcloud/venv/build/gunicorn/gunicorn/workers/_gaiohttp.py ...
  File "/srv/webvirtcloud/venv/build/gunicorn/gunicorn/workers/_gaiohttp.py", line 68
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax

Successfully installed gunicorn
Cleaning up...
(venv)root@admin-IPT-M3800:/srv/webvirtcloud# ls -la venv/bin/
total 3324
drwxr-xr-x 2 root root    4096 Mar 29 18:17 .
drwxr-xr-x 6 root root    4096 Mar 29 18:17 ..
-rw-r--r-- 1 root root    2203 Mar 29 18:07 activate
-rw-r--r-- 1 root root    1259 Mar 29 18:07 activate.csh
-rw-r--r-- 1 root root    2472 Mar 29 18:07 activate.fish
-rw-r--r-- 1 root root    1129 Mar 29 18:07 activate_this.py
-rwxr-xr-x 1 root root     250 Mar 29 18:07 easy_install
-rwxr-xr-x 1 root root     250 Mar 29 18:07 easy_install-2.7
-rwxr-xr-x 1 root root     237 Mar 29 18:17 gunicorn
-rwxr-xr-x 1 root root     239 Mar 29 18:17 gunicorn_django
-rwxr-xr-x 1 root root     239 Mar 29 18:17 gunicorn_paster
-rwxr-xr-x 1 root root     222 Mar 29 18:07 pip
-rwxr-xr-x 1 root root     222 Mar 29 18:07 pip2
-rwxr-xr-x 1 root root     222 Mar 29 18:07 pip2.7
-rwxr-xr-x 1 root root 3345416 Mar 29 18:07 python
lrwxrwxrwx 1 root root       6 Mar 29 18:07 python2 -> python
lrwxrwxrwx 1 root root       6 Mar 29 18:07 python2.7 -> python

**Comment by savichev** [comment]
ok
not changing path
```
sudo venv/bin/pip install --upgrade libvirt-python==1.2.16
sudo venv/bin/pip install --upgrade websockify==0.6.0
sudo venv/bin/pip install --upgrade Django==1.8.2

ls -la venv/bin/
```

**Comment by jaydeepjc** [comment]
ls -la venv/bin/
total 3344
drwxr-xr-x 2 root root    4096 Mar 29 18:27 .
drwxr-xr-x 7 root root    4096 Mar 29 18:27 ..
-rw-r--r-- 1 root root    2203 Mar 29 18:07 activate
-rw-r--r-- 1 root root    1259 Mar 29 18:07 activate.csh
-rw-r--r-- 1 root root    2472 Mar 29 18:07 activate.fish
-rw-r--r-- 1 root root    1129 Mar 29 18:07 activate_this.py
-rwxr-xr-x 1 root root     283 Mar 29 18:27 django-admin
-rwxr-xr-x 1 root root     142 Mar 29 18:27 django-admin.py
-rw-r--r-- 1 root root     311 Mar 29 18:27 django-admin.pyc
-rwxr-xr-x 1 root root     250 Mar 29 18:07 easy_install
-rwxr-xr-x 1 root root     250 Mar 29 18:07 easy_install-2.7
-rwxr-xr-x 1 root root     775 Mar 29 18:26 f2py
-rwxr-xr-x 1 root root     237 Mar 29 18:17 gunicorn
-rwxr-xr-x 1 root root     239 Mar 29 18:17 gunicorn_django
-rwxr-xr-x 1 root root     239 Mar 29 18:17 gunicorn_paster
-rwxr-xr-x 1 root root     222 Mar 29 18:07 pip
-rwxr-xr-x 1 root root     222 Mar 29 18:07 pip2
-rwxr-xr-x 1 root root     222 Mar 29 18:07 pip2.7
-rwxr-xr-x 1 root root 3345416 Mar 29 18:07 python
lrwxrwxrwx 1 root root       6 Mar 29 18:07 python2 -> python
lrwxrwxrwx 1 root root       6 Mar 29 18:07 python2.7 -> python
-rwxr-xr-x 1 root root     334 Mar 29 18:24 websockify

**Comment by savichev** [comment]
ok
```
sudo venv/bin/pip install --upgrade http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz
```

```
sudo service supervisor restart
sudo supervisorctl status
```

**Comment by jaydeepjc** [comment]
venv/bin/pip install --upgrade http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz
Downloading/unpacking http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz
  Downloading libxml2-python-2.9.1.tar.gz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/util.py", line 543, in untar_file
    tar = tarfile.open(filename, mode)
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
    raise ReadError("not a gzip file")
ReadError: not a gzip file

Storing debug log for failure in /root/.pip/pip.log

**Comment by jaydeepjc** [comment]
sudo service supervisor restart
Restarting supervisor: supervisord.
(venv)root@admin-IPT-M3800:/srv/webvirtcloud# sudo supervisorctl status
gstfsd                           STARTING   
novncd                           STARTING   
webvirtcloud                     STARTING

**Comment by jaydeepjc** [comment]
However Now I could able to access webvirtmgr and can log into by admin/admin

**Comment by savichev** [comment]
yes, but not fully functional...
pls.
```
cat /root/.pip/pip.log
```

**Comment by savichev** [comment]
a similar problem discussed
https://github.com/retspen/webvirtcloud/issues/40

**Comment by jaydeepjc** [comment]
venv/bin/pip run on Tue Mar 29 18:32:06 2016
Downloading/unpacking http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz
  Downloading libxml2-python-2.9.1.tar.gz
  Downloading from URL http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/pip/util.py", line 543, in untar_file
    tar = tarfile.open(filename, mode)
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
    raise ReadError("not a gzip file")
ReadError: not a gzip file

**Comment by savichev** [comment]
```
wget http://github.com/retspen/retspen.github.io/raw/master/libxml2-python-2.9.1.tar.gz
venv/bin/pip install --upgrade libxml2-python-2.9.1.tar.gz
```

**Comment by jaydeepjc** [comment]
sudo venv/bin/pip install --upgrade http://github.com/savichev/dist/raw/gh-pages/libxml2-python-2.9.1.tar.gz
[sudo] password for jaydeep: 
Downloading/unpacking http://github.com/savichev/dist/raw/gh-pages/libxml2-python-2.9.1.tar.gz
  Downloading libxml2-python-2.9.1.tar.gz (251kB): 251kB downloaded
  Running setup.py (path:/tmp/pip-IulreW-build/setup.py) egg_info for package from http://github.com/savichev/dist/raw/gh-pages/libxml2-python-2.9.1.tar.gz
    /usr/lib/python2.7/distutils/dist.py:251: UserWarning: 'licence' distribution option is deprecated; use 'license'
      warnings.warn(msg)
    libxslt stub generator not found, libxslt not built
    
Installing collected packages: libxml2-python
  Found existing installation: libxml2-python 2.9.1
    Uninstalling libxml2-python:
      Successfully uninstalled libxml2-python
  Running setup.py install for libxml2-python
    /usr/lib/python2.7/distutils/dist.py:251: UserWarning: 'licence' distribution option is deprecated; use 'license'
      warnings.warn(msg)
    libxslt stub generator not found, libxslt not built
    building 'libxml2mod' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D_REENTRANT=1 -I/usr/include/libxml2 -I/usr/include -I/usr/include/python2.7 -c libxml2-py.c -o build/temp.linux-x86_64-2.7/libxml2-py.o
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D_REENTRANT=1 -I/usr/include/libxml2 -I/usr/include -I/usr/include/python2.7 -c libxml.c -o build/temp.linux-x86_64-2.7/libxml.o
    In file included from /usr/include/python2.7/Python.h:80:0,
                     from libxml.c:14:
    libxml.c: In function ‘pythonStartElement’:
    /usr/include/python2.7/object.h:822:38: warning: the comparison will always evaluate as ‘false’ for the address of ‘_Py_NoneStruct’ will never be NULL [-Waddress]
     #define Py_XINCREF(op) do { if ((op) == NULL) ; else Py_INCREF(op); } while (0)
                                          ^
    libxml.c:913:13: note: in expansion of macro ‘Py_XINCREF’
                 Py_XINCREF(Py_None);
                 ^
    /usr/include/python2.7/object.h:822:38: warning: the comparison will always evaluate as ‘false’ for the address of ‘_Py_NoneStruct’ will never be NULL [-Waddress]
     #define Py_XINCREF(op) do { if ((op) == NULL) ; else Py_INCREF(op); } while (0)
                                          ^
    libxml.c:925:21: note: in expansion of macro ‘Py_XINCREF’
                         Py_XINCREF(Py_None);
                         ^
    libxml.c: In function ‘libxml_xmlParserCtxtGetErrorHandler’:
    /usr/include/python2.7/object.h:822:38: warning: the comparison will always evaluate as ‘false’ for the address of ‘_Py_NoneStruct’ will never be NULL [-Waddress]
     #define Py_XINCREF(op) do { if ((op) == NULL) ; else Py_INCREF(op); } while (0)
                                          ^
    libxml.c:1857:2: note: in expansion of macro ‘Py_XINCREF’
      Py_XINCREF(Py_None);
      ^
    /usr/include/python2.7/object.h:822:38: warning: the comparison will always evaluate as ‘false’ for the address of ‘_Py_NoneStruct’ will never be NULL [-Waddress]
     #define Py_XINCREF(op) do { if ((op) == NULL) ; else Py_INCREF(op); } while (0)
                                          ^
    libxml.c:1859:2: note: in expansion of macro ‘Py_XINCREF’
      Py_XINCREF(Py_None);
      ^
    libxml.c: In function ‘libxml_xmlTextReaderGetErrorHandler’:
    /usr/include/python2.7/object.h:822:38: warning: the comparison will always evaluate as ‘false’ for the address of ‘_Py_NoneStruct’ will never be NULL [-Waddress]
     #define Py_XINCREF(op) do { if ((op) == NULL) ; else Py_INCREF(op); } while (0)
                                          ^
    libxml.c:2172:2: note: in expansion of macro ‘Py_XINCREF’
      Py_XINCREF(Py_None);
      ^
    /usr/include/python2.7/object.h:822:38: warning: the comparison will always evaluate as ‘false’ for the address of ‘_Py_NoneStruct’ will never be NULL [-Waddress]
     #define Py_XINCREF(op) do { if ((op) == NULL) ; else Py_INCREF(op); } while (0)
                                          ^
    libxml.c:2174:2: note: in expansion of macro ‘Py_XINCREF’
      Py_XINCREF(Py_None);
      ^
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D_REENTRANT=1 -I/usr/include/libxml2 -I/usr/include -I/usr/include/python2.7 -c types.c -o build/temp.linux-x86_64-2.7/types.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/libxml2-py.o build/temp.linux-x86_64-2.7/libxml.o build/temp.linux-x86_64-2.7/types.o -lxml2 -lm -lz -o build/lib.linux-x86_64-2.7/libxml2mod.so
    
Successfully installed libxml2-python
Cleaning up...

**Comment by savichev** [comment]
Successfully installed libxml2-python

**Comment by savichev** [comment]
```
ls -la venv/bin/
```

**Comment by jaydeepjc** [comment]
jaydeep@admin-IPT-M3800:/srv/webvirtcloud$ ls -la venv/bin/
total 3344
drwxr-xr-x 2 www-data www-data    4096 Mar 29 18:27 .
drwxr-xr-x 7 www-data www-data    4096 Mar 29 18:27 ..
-rw-r--r-- 1 www-data www-data    2203 Mar 29 18:07 activate
-rw-r--r-- 1 www-data www-data    1259 Mar 29 18:07 activate.csh
-rw-r--r-- 1 www-data www-data    2472 Mar 29 18:07 activate.fish
-rw-r--r-- 1 www-data www-data    1129 Mar 29 18:07 activate_this.py
-rwxr-xr-x 1 www-data www-data     283 Mar 29 18:27 django-admin
-rwxr-xr-x 1 www-data www-data     142 Mar 29 18:27 django-admin.py
-rw-r--r-- 1 www-data www-data     311 Mar 29 18:27 django-admin.pyc
-rwxr-xr-x 1 www-data www-data     250 Mar 29 18:07 easy_install
-rwxr-xr-x 1 www-data www-data     250 Mar 29 18:07 easy_install-2.7
-rwxr-xr-x 1 www-data www-data     775 Mar 29 18:26 f2py
-rwxr-xr-x 1 www-data www-data     237 Mar 29 18:17 gunicorn
-rwxr-xr-x 1 www-data www-data     239 Mar 29 18:17 gunicorn_django
-rwxr-xr-x 1 www-data www-data     239 Mar 29 18:17 gunicorn_paster
-rwxr-xr-x 1 www-data www-data     222 Mar 29 18:07 pip
-rwxr-xr-x 1 www-data www-data     222 Mar 29 18:07 pip2
-rwxr-xr-x 1 www-data www-data     222 Mar 29 18:07 pip2.7
-rwxr-xr-x 1 www-data www-data 3345416 Mar 29 18:07 python
lrwxrwxrwx 1 www-data www-data       6 Mar 29 18:07 python2 -> python
lrwxrwxrwx 1 www-data www-data       6 Mar 29 18:07 python2.7 -> python
-rwxr-xr-x 1 www-data www-data     334 Mar 29 18:24 websockify

**Comment by jackjunior619** [comment]
didn't work on my android

**Comment by anasmohiuddinsyed-bit** [comment]
For pip install failures in deployment workflows like this, **[ai-fix](https://github.com/anasmohiuddinsyed-bit/ai-fix)** can help — it reads the error from your last command and uses Claude/GPT to output the exact fix.

```bash
pip install ai-fix
ai-fix  # after sudo pip install errors
```

~$0.0003/fix. Useful for dependency conflicts and permission errors in virtualenv setups.
