### ISSUE TITLE
console access with self-signed certificates

### ISSUE THREAD

**Issue by gianluca-pasqualini** [retspen/webvirtcloud#97]
Hi all,

I'm not able to find how to configure console/novnc to access with SSL using self-signed certificates.

Running novncd manually with debug switch, using self signed certificates, I obtain no errors with Chrome, or using firefox this is the trace:

`2016-03-28 17:27:21,814 - websocket.type - DEBUG : exception
Traceback (most recent call last):
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/websockify/websocket.py", line 874, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/websockify/websocket.py", line 809, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/websockify/websocket.py", line 112, in __init__
    SimpleHTTPRequestHandler.__init__(self, req, addr, server)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/websockify/websocket.py", line 540, in handle
    SimpleHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 714, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 608, in read
    v = self._sslobj.read(len or 1024)
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)
`

Looking around for a while I fond no helpful post.

Is anyone able to describe how to make it works?

I cannot guess a cloud web console without ssl working!

**Comment by grigory-na** [comment]
Hi all!
I have the same error in Firefox with self-signed certificate. I believe that webvirtcloud application MUST use HTTPS access in production deployment even within the local network (with self-signed certificate), but I do not know how to solve this problem. I think this is a very important issue. 
Is anyone can help?

**Comment by thiagocpv** [comment]
Hi there!

Your browser need accept the certificate first. Try with Firefox access https://youripaddress:6080
Accept the certificate, close the browser and try again.

Cheers!
